version: "3"

services:
  vue:
    image: smartuse/gemeindescan-webui-vue:0.0.1
    hostname: vue
    environment:
      - TERM=xterm-256color
    volumes:
      - ./vue:/opt/vue
    working_dir: /opt/vue
    ports:
      - "8080:8080"

  django:
    image: smartuse/gemeindescan-webui-django:0.0.1
    hostname: django
    environment:
      - TERM=xterm-256color
      - START_DJANGO=YES
      - DJANGO_DB_NAME=webui
      - DJANGO_DB_USER=webui
      - DJANGO_DB_PASSWORD=pgpass
      - DJANGO_DB_HOST=pdb
      - DJANGO_DEBUG=False
      - DJANGO_HTTPS=True
      - DJANGO_EMAIL_HOST=XXX
      - DJANGO_SECRET_KEY=XXX
    volumes:
      - ./django:/opt/django
      # - ./var/django:/var/services/django
    working_dir: /opt/django/
    ports:
    - "8081:8081"
