version: "3"

volumes:
  vscode-remote-fastapi:
  vscode-remote-vue:

services:
  pdb:
    image: postgres:12-alpine
    hostname: pdb
    environment:
      - PGDATA=/var/services/postgres/data
      - POSTGRES_USER=webui
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=webui
    volumes:
      - ./var/postgres:/var/services/postgres
    ports:
       - "5434:5432"

  vue:
    volumes:
      - vscode-remote-vue:/root/.vscode-server
    ports:
      - "10001:10001" # vscode
    command: tail -f /dev/null

  fastapi:
    environment:
      - FASTAPI_DB_NAME=webui
      - FASTAPI_DB_USER=webui
      - FASTAPI_DB_PASSWORD=pgpass
      - FASTAPI_DB_HOST=pdb
      - FASTAPI_DEBUG=True
      - FASTAPI_HTTPS=False
      - FASTAPI_EMAIL_HOST=maildev
    volumes:
      - vscode-remote-fastapi:/root/.vscode-server
    links:
     - pdb
    ports:
      - "8081:8081"
      - "10002:10002" # vscode
    command: tail -f /dev/null
