version: "2"

volumes:
  vscode-remote-django:
  vscode-remote-vue:
  var-gemeindescan-webui:

services:
  pdb:
    extends:
      file: docker-images.yml
      service: pdb
    environment:
      - PGDATA=/var/services/postgres/data
      - POSTGRES_USER=webui
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=webui
    volumes:
      - var-gemeindescan-webui:/var/services
    ports:
       - "5434:5432"

  vue:
    extends:
      file: docker-images.yml
      service: vue
    environment:
      - TERM=xterm-256color
      - START_SCREENSHOTSERVICE=NO
      - PUBLIC_URL=http://localhost:8080
    working_dir: /opt/vue
    volumes:
      - ./vue:/opt/vue
      - var-gemeindescan-webui:/var/services/
      - vscode-remote-vue:/root/.vscode-server
    ports:
      # - "9222:9222" # debug chrome
      - "8079:8079" # snapshost service
      - "10001:10001" # vscode

  django:
    extends:
      file: docker-images.yml
      service: django
    environment:
      - TERM=linux
      - START_DJANGO=NO
      - DJANGO_DB_NAME=webui
      - DJANGO_DB_USER=webui
      - DJANGO_DB_PASSWORD=pgpass
      - DJANGO_DB_HOST=pdb
      - DJANGO_DEBUG=True
      - DJANGO_HTTPS=False
      - DJANGO_EMAIL_HOST=maildev
      - DJANGO_SECRET_KEY=adddxxccxx4rt0ioywg3yf5kjq64-t5
      - DJANGO_ALLOWED_HOSTS=local.gemeindescan.ch,localhost,django
    working_dir: /opt/app
    volumes:
      - ./django:/opt/app
      - var-gemeindescan-webui:/var/services
      - vscode-remote-django:/root/.vscode-server
    links:
     - pdb
    ports:
      - "10002:10002" # vscode
    # entrypoint: tail
    # command: -f /dev/null

  www:
    image: openresty/openresty:1.15.8.3-alpine
    hostname: www
    volumes:
      - ./etc/nginx:/etc/nginx/conf.d
      - var-gemeindescan-webui:/var/services
    links:
      - django
      - vue
    ports:
      - 8080:80
    command: tail -f /dev/null
