version: "3"

volumes:
  vscode-remote-django:
  vscode-remote-vue:

services:
  pdb:
    image: postgres:12-alpine
    hostname: pdb
    environment:
      - PGDATA=/var/services/postgres/data
      - POSTGRES_USER=webui
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=webui
    volumes:
      - ./var/postgres:/var/services/postgres
    ports:
       - "5434:5432"

  vue:
    image: smartuse/gemeindescan-webui-vue:0.0.1
    hostname: vue
    environment:
      - TERM=xterm-256color
    working_dir: /opt/vue
    volumes:
      - ./vue:/opt/vue
      - vscode-remote-vue:/root/.vscode-server
    ports:
      - "8080:8080"
      - "10001:10001" # vscode
    command: tail -f /dev/null

  django:
    environment:
      - TERM=xterm-256color
      - START_DJANGO=NO
      - DJANGO_DB_NAME=webui
      - DJANGO_DB_USER=webui
      - DJANGO_DB_PASSWORD=pgpass
      - DJANGO_DB_HOST=pdb
      - DJANGO_DEBUG=True
      - DJANGO_HTTPS=False
      - DJANGO_EMAIL_HOST=maildev
      - DJANGO_SECRET_KEY=adddxxccxx4rt0ioywg3yf5kjq64-t5
    volumes:
      - vscode-remote-django:/root/.vscode-server
    links:
     - pdb
    ports:
      - "8081:8081"
      - "10002:10002" # vscode
    command: tail -f /dev/null
